import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapActivation from '@/components/BootstrapActivation';
import {BaseProvider} from "@/context/BaseContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
      <html lang="en">
          <body className={inter.className}>
              <BaseProvider>
                  <Header/>
                  {children}
                  <BootstrapActivation />
                  <Footer/>
              </BaseProvider>
          </body>
      </html>
  );
}
